# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Not Quite Right
tagline:          'Comically Liberal. Liberally comical.'
description:      'Comically Liberal. Liberally comical. Occasionally edited.'
url:              http://notquiteright.github.io/

author:
  name:           'Not Quite Right'
  url:            http://notquiteright.github.io/

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/notquiteright/notquiteright.github.io
  active:         false
